server:
  port: 8888

spring:
  sql:
    init:
      mode: always
#  main:
#    allow-circular-references: true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/eatplace?characterEncoding=UTF-8&serverTimezone=UTC
    username: "root"
    password: "1234"

#  datasource:
#    url: jdbc:h2:tcp://localhost/~/eatplace
#    #    url: jdbc:h2:~/test
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:

  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: create-drop
#      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql
    generate-ddl: true
    defer-datasource-initialization: true

jwt:
  header: Authorization
  # HS512 secretkey
  # echo 'eat-place-spring-boot-jwt-secret-eat-place-spring-boot-jwt-secret'|base64
  secret: ZWF0LXBsYWNlLXNwcmluZy1ib290LWp3dC1zZWNyZXQtZWF0LXBsYWNlLXNwcmluZy1ib290LWp3dC1zZWNyZXQK
  token-validity-in-seconds: 86400

graphql:
  servlet:
    enabled: true
    mapping: /graphql
    cors-enabled: false
    cors:
      allowed-origins: http://localhost:8888
      allowed-methods: GET, HEAD, POST, PATCH
    exception-handlers-enabled: true
    context-setting: PER_REQUEST_WITH_INSTRUMENTATION
  tools:
      schema-location-pattern: "**/*.graphqls"
      introspection-enabled: true

logging:
  level:
    com.eat.eatplace: DEBUG